accounts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.loginPage, name='login'),
    path('register/', views.registerPage, name='register'),
    path('logout/',views.logoutUser, name = 'logout'),
    path('upload/', views.upload, name = "Upload"),
    path('download/', views.download, name = "Download"),
	path('export/', views.export_xls, name='Export'),
	path('ZIP/', views.getfiles, name = 'ZIP'),
]

uldl/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings 

urlpatterns = [
    path('admin/', admin.site.urls),
	path('', include('accounts.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

class Protocol(models.Model):
	pid = models.CharField(max_length=100, null = True)
	title = models.CharField(max_length=300, null = True)

	def __str__(self):
		return self.pid


class ai(models.Model):
	name = models.CharField(max_length=100, null = True)

	def __str__(self):
		return self.name


class crop(models.Model):
	name = models.CharField(max_length=100, null = True)

	def __str__(self):
		return self.name


class author(models.Model):
	name = models.CharField(max_length=100, null = True)

	def __str__(self):
		return self.name


class country(models.Model):
	name = models.CharField(max_length=100, null = True)

	def __str__(self):
		return self.name		


class year(models.Model):
	name = models.CharField(max_length=100, null = True)

	def __str__(self):
		return self.name


class Presentation(models.Model):
	"""
	Database for upload/download
	"""
	STATUS = (
		('Draft','Draft'),
		('Final', 'Final'),
		)
	author = models.ForeignKey(author, null=True, on_delete = models.SET_NULL)
	year = models.ForeignKey(year, null=True, on_delete = models.SET_NULL)
	country = models.ForeignKey(country, null=True, on_delete = models.SET_NULL)
	protocol = models.ManyToManyField(Protocol)
	ai = models.ManyToManyField(ai)
	crop = models.ManyToManyField(crop)
	status = status = models.CharField(max_length=10, null = True, choices = STATUS, blank = False, default = 'Unspecified')
	pptx = models.FileField(upload_to = "documents/", null = True)

	def get_title(self):
		primary = self.protocol.all()[0]

		return (primary.title)


	def get_protocols(self):
		ret = ''

		for protocol in self.protocol.all():
			ret = ret + protocol.pid + ', '

		return ret[:-2]

	def get_crops(self):
		ret = ''

		for crop in self.crop.all():
			ret = ret + crop.name + ', '

		return ret[:-2]

	def get_ais(self):
		ret = ''

		for ai in self.ai.all():
			ret = ret + ai.name + ', '

		return ret[:-2]

accounts/forms.py
from django.forms import ModelForm
from .models import *
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth.models import User
from django.forms.widgets import ClearableFileInput


class UploadPres(ModelForm):
	class Meta:
		model = Presentation
		fields = '__all__'
		widgets = {
			'pptx': ClearableFileInput(),
		}
		
		

class CreateUserForm(UserCreationForm):
	class Meta:
		model = User
		fields = ['username','email','password1','password2']

accounts/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required 
# Create your views here.
from .models import * 
from .forms import *
from .filters import *
import zipfile36 as zipfile
import os
import boto
import io

import xlwt


def loginPage(request):
	if request.user.is_authenticated:
		return redirect('Download')
	else:
		if request.method == "POST":
			username = request.POST.get("username")
			password = request.POST.get("password")
			
			user = authenticate(request, username = username, password = password)

			if user is not None:
				login(request, user)
				return redirect('Download')
			else:
				messages.info(request, 'Username or Password was not correct')

		context = {}
		return render(request, 'accounts/login.html', context)


def logoutUser(request):
	logout(request)
	return redirect('login')


def registerPage(request):
	if request.user.is_authenticated:
		return redirect('Download')
	else:
		form = CreateUserForm()
		if request.method == "POST":
			form = CreateUserForm(request.POST)
			if form.is_valid():
				form.save()
				messages.success(request, 'Account was successful created')
				return redirect('login')

		context = {'form': form}
		return render(request, 'accounts/register.html', context)


@login_required(login_url='login')
def upload(request):
	submit = UploadPres()
	
	if request.method == 'POST':
		submit = UploadPres(request.POST, request.FILES)
		if submit.is_valid():
			submit.save()
			messages.info(request, 'Presentation Uploaded Successfully!')
			return redirect('Download')
	context = {'submit': submit}
	return render(request, 'accounts/upload.html', context)


@login_required(login_url='login')
def download (request):
	presentations = Presentation.objects.all()

	myFilter = Presentationfilter(request.GET, queryset=presentations)
	presentations = myFilter.qs
	request.session['presies'] = [f.id for f in presentations]

	display = presentations.count()

	context = {'presentations': presentations, 'myFilter': myFilter, 'display': display}
	return render(request, 'accounts/download.html', context)


def getfiles(request):
	ids = request.session['presies']
	presies = Presentation.objects.filter(id__in = ids)
	file_names = []
	for x in presies:
		file_names.append(x.pptx)

	zip_subdir = "tmp/presentation_folder"
	zip_filename = zip_subdir + ".zip"
	byte_stream = io.BytesIO()
	zf = zipfile.ZipFile(byte_stream, "w")  


	for filename in file_names:  
		conn = boto.connect_s3('AKIAVH6CVLPUTAWB5U4P', 'BF/zeRdEm5sEtzKymAMpJ6heO19Bv3XgSbvjkF85')
		bucket = conn.get_bucket('danielsantander-uldl')
		s3_file_path = bucket.get_key(filename)
		response_headers = {
		'response-content-type': 'application/force-download',
		'response-content-disposition':'attachment;filename="%s"'% filename
		}
		url = s3_file_path.generate_url(60, 'GET',
			response_headers=response_headers,
			force_http=True)

		# download the file
		file_response = requests.get(url)  

		if file_response.status_code == 200:

		# create a copy of the file
			string = str(filename)[10:]
			f1 = open(string , 'wb')
			f1.write(file_response.content)
			f1.close()

			# write the file to the zip folder
			fdir, fname = os.path.split(string)
			zip_path = os.path.join(zip_subdir, fname)
			zf.write(string, zip_path)     

	# close the zip folder and return
	zf.close()
	response = HttpResponse(byte_stream.getvalue(), content_type="application/x-zip-compressed")
	response['Content-Disposition'] = 'attachment; filename=%s' % zip_filename
	return response 


def export_xls(request):
	response = HttpResponse(content_type='application/ms-excel')
	response['Content-Disposition'] = 'attachment; filename="PresentationData.xls"'
	wb = xlwt.Workbook(encoding='utf-8')
	ws = wb.add_sheet('presentations')
	# Sheet header, first row
	row_num = 0
	font_style = xlwt.XFStyle()
	font_style.font.bold = True

	columns = ['Title','Author','Protocol','AI','Crop','Year','Status','Country']

	for col_num in range(len(columns)):
		ws.write(row_num, col_num, columns[col_num], font_style)

	font_style = xlwt.XFStyle()

	ids = request.session['presies']
	
	presies = Presentation.objects.filter(id__in = ids)

	for x in presies:
		row_num += 1

		title = x.get_title()
		aid = str(x.author)
		status = x.status
		cid2 = str(x.country)
		yid = str(x.year)

		protocols = x.protocol.all()
		pid = ""
		for a in range(len(protocols)):
			if a == 0:
				pid += str(protocols[a])
			else:
				pid += ", " + str(protocols[a]) 

		ais = x.ai.all()
		aid2 = ""
		for b in range(len(ais)):
			if b == 0:
				aid2 += str(ais[b])
			else :
				aid2 += ", " + str(ais[b])

		crops = x.crop.all()
		cid = []
		for c in range(len(crops)):
			if c == 0:
				cid += str(crops[c])
			else:
				cid += ", " + str(crops[c])

		edit = (title,aid,pid,aid2,cid,yid,status,cid2)
		for col_num in range(len(edit)):
			ws.write(row_num, col_num, edit[col_num], font_style)

	wb.save(response)
	return response



"""
		row_num += 1

		aindex = row[1]
		for a in authors:
			if a['id'] == aindex:
				aid = a['name']

		pindex = row[2]
		for p in protocols:
			if p['id'] == pindex:
				pid = p['name']

		a2index = row[3]
		for a2 in ais:
			if a2['id'] == a2index:
				aid2 = a2['name']

		cindex = row[4]
		for c in countries:
			if c['id'] == cindex:
				cid = c['name']

		c2index = row[7]
		for c2 in countries:
			if c2['id'] == c2index:
				cid2 = c2['name']

		yindex = row[5]
		for yr in years:
			if yr['id'] == yindex:
				yid = yr['name']
"""

accounts/templates/accounts/download.html
{% extends 'accounts/main.html' %}
{% load static %} 

{% block content%}

<head>
  <link rel="stylesheet" type="text/css" href="{% static 'css/download.css' %}">
  <script src="{% static 'js/dragtable.js' %}"></script>
  <script src="{% static 'js/sorttable.js' %}"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>

<style type="text/css">
	.display{
		text-align: right; 
		font-weight: bold;
	}
</style>

		
<br>
<div class="row">
	<div class="col-md">
		<div class="d-flex justify-content-center">
			<div class="header">
				<h1>Presentation Upload/Download</h1>
			</div>
		</div>
		<br>
		{% for message in messages %}
			<p id="messages">{{message}}</p>
		{% endfor %}
		<div class="card card-body">
			<div>
			<form style = "text-align: left">
				<a class="btn btn-primary" type="button" href="{% url 'Upload' %}">Upload New Presentation</a>
				<button class="btn btn-primary" type="button" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
					Filter Presentations
  				</button>
				<div class="collapse" id="collapseExample">
  					<div class="card card-body">
    					{{myFilter.form}}
    					<button class = "btn btn-primary" type = "submit">Search</button>
  					</div>
				</div>
			</form>
			</div>		
			<hr>
			<div style="overflow-x:auto;">
			<table class="draggable sortable" id="myTable2">
				<tr>
					<th>Title</th>
					<th>Author</th>
					<th>Protocol</th>
					<th>Active Ingredients</th>
					<th>Crop</th>
					<th>Year</th>
					<th>Status</th>
					<th>Country</th>
					<th>Download</th>
				</tr>		
				{% for i in presentations %}
					<tr>
						<td>{{i.get_title}}</td>
						<td>{{i.author}}</td>
						<td>{{i.get_protocols}}</td>
						<td>{{i.get_ais}}</td>
						<td>{{i.get_crops}}</td>
						<td>{{i.year}}</td>
						<td>{{i.status}}</td>
						<td>{{i.country}}</td>
						<td style="text-align:center">
							<a href = "{{i.pptx.url}}">
							<svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-download" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
								<path fill-rule="evenodd" d="M.5 8a.5.5 0 0 1 .5.5V12a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V8.5a.5.5 0 0 1 1 0V12a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V8.5A.5.5 0 0 1 .5 8z"/>
  								<path fill-rule="evenodd" d="M5 7.5a.5.5 0 0 1 .707 0L8 9.793 10.293 7.5a.5.5 0 1 1 .707.707l-2.646 2.647a.5.5 0 0 1-.708 0L5 8.207A.5.5 0 0 1 5 7.5z"/>
 								<path fill-rule="evenodd" d="M8 1a.5.5 0 0 1 .5.5v8a.5.5 0 0 1-1 0v-8A.5.5 0 0 1 8 1z"/>
							</svg>
						</a>
						</td>
					</tr>
				{% endfor %}
			</table>
			</div>
		</div>
		<div class="card card-body">
			<form style = "text-align: right">
				<p class = "display">Currently displaying: {{display}} Presentations</p>
				<a class = "btn btn-primary btn-sm"  href = "{% url 'Export' %}" role = "button">Export Table <i class="fa fa-file-excel-o"></i></a>
				<a class = "btn btn-primary btn-sm" href = "{% url 'ZIP' %}" role = "button">Download Filtered Presentations <i class="fa fa-file-archive-o" aria-hidden="true"></i></a>
			</form>
		</div>
	</div>		
</div>

<script type="text/javascript">
	var message_ele = document.getElementById("messages");

	setTimeout(function(){ 
   		message_ele.style.display = "none"; 
	}, 3000);
</script>

{% endblock %}

accounts/templates/accounts/export_xls.html
{% extends 'accounts/main.html' %}
{% load static %}
{% block content %}

<a href="{% url 'export' %}">Export all users</a>

{% endblock %}

accounts/templates/accounts/login.html
<!DOCTYPE html>
<html>
    
<head>
	<title>UL/DL Login</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">


	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: #ebeff5 !important;
		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: #849dba;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #fff;
			
		}

		.login_btn {
			width: 100%;
			background: #33ccff !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #f7ba5b !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

		#messages{
			background-color: grey;
			color: #fff;
			padding: 10px;
			margin-top: 10px;
		}
	</style>

</head>
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">
					<h3 id="form-title">
						<p>Upload/Download</p> 
						<p class="d-flex justify-content-center">LOGIN</p> 
					</h3>
				</div>
				<div class="d-flex justify-content-center form_container">
					<form method="POST" action="">
						{% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							<input type="text" name="username" placeholder="Username..." class="form-control">
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
								<input type="password" name="password" placeholder="Password..." class="form-control" >
						</div>

							<div class="d-flex justify-content-center mt-3 login_container">
				 				<input class="btn login_btn" type="submit" value="Login">
				   			</div>
					</form>

				</div>
				{% for message in messages %}
					<p id="messages">{{message}}</p>
				{% endfor %}
				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Don't have an account? <a href="{% url 'register' %}" class="ml-2">Sign Up</a>
					</div>
			
				</div>
			</div>
		</div>
	</div>
</body>

</html>

accounts/templates/accounts/main.html
{% load static %} 

<!DOCTYPE html>
<html>
<style type="text/css">
	.footer {
		text-align: right;
		font-size: .9vw;
	}
	.footer2 {
		text-align: right;
		font-size: .8vw;
	}
</style>

<head>
	<link rel="shortcut icon" href="{%  static 'images/fav2.jpg' %}">
	<title>Presentation UL/DL</title>

	<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/css/select2.min.css" rel="stylesheet" />

	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">

</head>
<body>
	{% include 'accounts/navbar.html' %}

	{% block content %}




	{% endblock %}

	<hr>
	<h5 class = "footer">Developed by North America Biological Data Analytics</h5>
	<h5 class = "footer2">For Support Contact: daniel.santander@syngenta.com</h5>
	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

	<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/js/select2.min.js"></script>

		<script>
			// In your Javascript (external .js resource or <script> tag)
			$(document).ready(function() {
	   			$('#id_crop').select2();
			});
		</script>
		<script>
			// In your Javascript (external .js resource or <script> tag)
			$(document).ready(function() {
	   			$('#id_protocol').select2();
			});
		</script>
		<script for = "#id_ai">
			// In your Javascript (external .js resource or <script> tag)
			$(document).ready(function() {
				$('#id_ai').select2();
			});
		</script>
</body>
</html>

accounts/templates/accounts/navbar.html
{% load static %}

<style>
  .Hello-msg{
    font-size: 18px;
    color: #fff;
    margin-right: 20px;
  }
</style>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">
    <img src="{% static 'images/black.png' %}" height="50" alt="Logo">
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'Download' %}">Download</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{%  url 'Upload' %}">Upload</a>
      </li>
    </ul>
  </div>

  <span class='Hello-msg'>Hello, {{request.user}}</span>
  <span><a class='Hello-msg' href = "{% url 'logout' %}">Logout</a></span>

</nav>  

accounts/templates/accounts/register.html
<!DOCTYPE html>
<html>
    
<head>
	<title>UL/DL Register</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">

	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: #ebeff5 !important;
		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: #849dba;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #fff;
		}
		.login_btn {
			width: 100%;
			background: #33ccff !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #f7ba5b !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

	</style>

</head>
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">
					<h3 id="form-title">REGISTER ACCOUNT</h3>
				</div>
				<div class="d-flex justify-content-center form_container">

					<form method="POST" action="">
						{% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							{{form.username}}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-envelope-square"></i></span>
							</div>
							{{form.email}}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
							{{form.password1}}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
							{{form.password2}}
						</div>

				   		<div class="d-flex justify-content-center mt-3 login_container">
				 			<input class="btn login_btn" type="submit" value="Register Account">
				   		</div>
					</form>
				</div>
				{{form.errors}}
				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Already have an account? <a href="{% url 'login' %}" class="ml-2">Login</a>
					</div>
				</div>
			</div>
		</div>
	</div>
	<script>
						/* Because i didnt set placeholder values in forms.py they will be set here using vanilla Javascript
		//We start indexing at one because CSRF_token is considered and input field 
		 */

		//Query All input fields
		var form_fields = document.getElementsByTagName('input')
		form_fields[1].placeholder='Username..';
		form_fields[2].placeholder='Email..';
		form_fields[3].placeholder='Enter password...';
		form_fields[4].placeholder='Re-enter Password...';


		for (var field in form_fields){	
			form_fields[field].className += ' form-control'
		}
	</script>
</body>
</html>

accounts/templates/accounts/upload.html
{% extends 'accounts/main.html' %}
{% load static %}
{% block content %}


<link rel="stylesheet" type="text/css" href="{% static 'css/upload.css' %}">
<style type="text/css">
	label {
		font-size: 1.3vw;
		font-weight: bold;
	}
	#id_title{
		width:90%;
	}
	#id_status{
		border: 1px solid black;
	}
	#id_status_0{
		font-size: 1vw;
		font-weight: normal;
	}
	#id_status_1{
		font-size: 1vw;
		font-weight: normal !important;
	}
</style>

<br>
<div class="d-flex justify-content-center">
	<div class="header">
		<h1>Presentation Upload</h1>
	</div>
</div>
<hr>

<div class="card card-body">
	<form method="POST" enctype = "multipart/form-data">
		{% csrf_token %}

		<div class = "form-row">
			<div class="col-md-4 mb-3">
				<label for = "id_author">Author*</label>
				{{submit.author}}
			</div>
			<div class = "col-md-4 mb-3">
				<label for = "id_year">Year*</label>
				{{submit.year}}
			</div>
			<div class = "col-md-4 mb-3">
				<label for = "id_country">Country*</label>
				{{submit.country}}
			</div>
		</div>

		<div class="form-row">
			<div class = "col-md-4 mb-3">
				<label for = "id_ai">Active Ingredients*</label>
				{{submit.ai}}
			</div>
			<div class = "col-md-4 mb-3">
				<label for = "id_crop">Crops*</label>
				{{submit.crop}}
			</div>
			<div class = "col-md-4 mb-3" onchange="myNewFunction(this);">	
				<label for = "id_protocol">Protocol*</label>
				{{submit.protocol}}
			</div>
		</div>

		<div class = "form-row">
			<div class = "col-md-2 mb-3">
				<label for = "id_status">Status*</label>
				{{submit.status}}
			</div>
			<div class = "col-md-2 mb-3">
			</div>
			<div class = "col-md-4 mb-3" style="border: 1px;">
				<br>
				<label for ="id_pptx">Presentation*</label>
				<br>
				{{submit.pptx}}
			</div>
		</div>
		<hr>
		<div style="text-align: right">
			<input class="btn btn-primary btn-lg" type="submit" name="Upload" value ="Upload">
		</div>
	</form>
</div>

{% endblock %}